import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { CheckCircle2, XCircle, AlertTriangle, Download } from "lucide-react";
import { Button } from "@/components/ui/button";

interface RecruiterReportProps {
    userData: any;
    recruiterContext: any;
    recruiterAnalysis: any;
    swotAnalysis: any;
    hiringOdds: any;
    repoAudit: any;
    onClose: () => void;
}

export default function RecruiterReport({
    userData,
    recruiterContext,
    recruiterAnalysis,
    swotAnalysis,
    hiringOdds,
    repoAudit,
    onClose
}: RecruiterReportProps) {

    const handlePrint = () => {
        window.print();
    };

    if (!userData || !recruiterAnalysis) return <div>Loading Report...</div>;

    return (
        <div className="bg-white text-black min-h-screen p-8 max-w-4xl mx-auto font-sans">
            {/* Print Controls */}
            <div className="print:hidden flex justify-between items-center mb-8">
                <Button variant="outline" onClick={onClose}>Back to Dashboard</Button>
                <Button onClick={handlePrint} className="gap-2">
                    <Download className="w-4 h-4" /> Save as PDF
                </Button>
            </div>

            {/* Report Header */}
            <div className="flex justify-between items-start border-b-2 border-black pb-6 mb-8">
                <div>
                    <h1 className="text-4xl font-bold tracking-tight">Candidate Evaluation Report</h1>
                    <p className="text-gray-600 mt-2">Generated by Git Intel AI</p>
                </div>
                <div className="text-right">
                    <h2 className="text-xl font-bold">{userData.name || userData.login}</h2>
                    <p className="text-gray-600">github.com/{userData.login}</p>
                    <p className="text-sm text-gray-500 mt-1">{new Date().toLocaleDateString()}</p>
                </div>
            </div>

            {/* Evaluation Context */}
            <div className="grid grid-cols-2 gap-8 mb-8 bg-gray-50 p-6 rounded-xl border border-gray-200">
                <div>
                    <h3 className="text-sm uppercase tracking-wider text-gray-500 font-bold mb-2">Evaluated For</h3>
                    <p className="text-xl font-bold">{recruiterContext.company}</p>
                    <p className="text-gray-700">{recruiterContext.jobRole} ({recruiterContext.experience})</p>
                </div>
                <div>
                    <h3 className="text-sm uppercase tracking-wider text-gray-500 font-bold mb-2">Fit Assessment</h3>
                    <div className="flex items-center gap-3">
                        <span className={`text-4xl font-black ${recruiterAnalysis.fitScore >= 70 ? 'text-green-600' :
                                recruiterAnalysis.fitScore >= 40 ? 'text-yellow-600' : 'text-red-600'
                            }`}>
                            {recruiterAnalysis.fitScore}%
                        </span>
                        <div>
                            <p className="font-bold">{recruiterAnalysis.fitTier}</p>
                        </div>
                    </div>
                </div>
            </div>

            {/* Executive Summary */}
            <div className="mb-8">
                <h3 className="text-lg font-bold border-b border-gray-200 pb-2 mb-4">Executive Summary</h3>
                <p className="text-gray-800 leading-relaxed text-lg">
                    {recruiterAnalysis.analysis}
                </p>
            </div>

            {/* Strengths & Gaps Grid */}
            <div className="grid grid-cols-2 gap-8 mb-8">
                <div>
                    <h3 className="font-bold text-green-700 mb-3 flex items-center gap-2">
                        <CheckCircle2 className="w-5 h-5" /> Key Strengths
                    </h3>
                    <ul className="space-y-2">
                        {recruiterAnalysis.strengths?.map((s: string, i: number) => (
                            <li key={i} className="flex items-start gap-2 text-gray-700">
                                <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-green-500 flex-shrink-0" />
                                {s}
                            </li>
                        ))}
                    </ul>
                </div>
                <div>
                    <h3 className="font-bold text-red-700 mb-3 flex items-center gap-2">
                        <AlertTriangle className="w-5 h-5" /> Critical Gaps
                    </h3>
                    <ul className="space-y-2">
                        {recruiterAnalysis.gaps?.map((s: string, i: number) => (
                            <li key={i} className="flex items-start gap-2 text-gray-700">
                                <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-red-500 flex-shrink-0" />
                                {s}
                            </li>
                        ))}
                    </ul>
                </div>
            </div>

            {/* SWOT Matrix Summary */}
            {swotAnalysis && (
                <div className="mb-8 print:break-inside-avoid">
                    <h3 className="text-lg font-bold border-b border-gray-200 pb-2 mb-4">SWOT Analysis</h3>
                    <div className="grid grid-cols-2 gap-4">
                        <div className="p-4 bg-gray-50 rounded border border-gray-200">
                            <h4 className="font-bold text-sm mb-2">Strengths</h4>
                            <ul className="list-disc pl-4 text-sm text-gray-600">{swotAnalysis.strengths?.slice(0, 3).map((s: any, i: number) => <li key={i}>{typeof s === 'string' ? s : s.point}</li>)}</ul>
                        </div>
                        <div className="p-4 bg-gray-50 rounded border border-gray-200">
                            <h4 className="font-bold text-sm mb-2">Weaknesses</h4>
                            <ul className="list-disc pl-4 text-sm text-gray-600">{swotAnalysis.weaknesses?.slice(0, 3).map((s: any, i: number) => <li key={i}>{typeof s === 'string' ? s : s.point}</li>)}</ul>
                        </div>
                        <div className="p-4 bg-gray-50 rounded border border-gray-200">
                            <h4 className="font-bold text-sm mb-2">Opportunities</h4>
                            <ul className="list-disc pl-4 text-sm text-gray-600">{swotAnalysis.opportunities?.slice(0, 3).map((s: any, i: number) => <li key={i}>{typeof s === 'string' ? s : s.point}</li>)}</ul>
                        </div>
                        <div className="p-4 bg-gray-50 rounded border border-gray-200">
                            <h4 className="font-bold text-sm mb-2">Threats</h4>
                            <ul className="list-disc pl-4 text-sm text-gray-600">{swotAnalysis.threats?.slice(0, 3).map((s: any, i: number) => <li key={i}>{typeof s === 'string' ? s : s.point}</li>)}</ul>
                        </div>
                    </div>
                </div>
            )}

            {/* Interview Question */}
            {recruiterAnalysis.interviewQuestion && (
                <div className="bg-blue-50 border border-blue-200 p-6 rounded-xl print:break-inside-avoid">
                    <h3 className="text-blue-800 font-bold mb-2">💡 Recommended Interview Question</h3>
                    <p className="text-blue-900 italic font-medium">"{recruiterAnalysis.interviewQuestion}"</p>
                </div>
            )}

            <div className="mt-12 text-center text-xs text-gray-400 border-t pt-4 print:fixed print:bottom-0 print:w-full">
                Git Intel Report • Generated {new Date().toLocaleString()}
            </div>
        </div>
    );
}
